---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  namespace: monitoring
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
        #app.selector: frontend
  endpoints:
  - port: frontend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
        #app.selector: backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trial
        #app.selector: trial
  endpoints:
  - port: trial
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
