apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backendport
  labels:
    name: trial
    release: prometheus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        image: vahiwe/dashboard:trial
        imagePullPolicy: Always
        ports:
        - name: trialport
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAEGER_HOST
          value: my-traces-agent.observability.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
  labels:
    app: trial
spec:
  selector:
    app: trial
  ports:
    - port: 8080
      targetPort: trialport
      nodePort: 30002
  type: NodePort
